baseURL = 'https://rafaelbroseghini.com/'
languageCode = 'en-us'
title = 'rafaelbroseghini.com'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "til"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Collection to display on home
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

showFooter = false

faviconPath = 'favicon'

[params.umami]
enable = true
websiteId = "9b9456bb-75e9-43da-9e93-44d014bd324f"
jsLocation = "https://cloud.umami.is/script.js"
# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rafaelbroseghini/"

[[params.social]]
name = "github"
url = "https://github.com/rafaelbroseghini"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "tags"
url = "/tags"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'catppuccin-frappe'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

